### ISSUE TITLE
Some components dont export into the level

### ISSUE THREAD

**Issue by RobiFox** [Tundra-Editor/Issues#37]
**Describe the bug**
Some components are missing in the exported level.
I've noticed it with RandomSetActive, MapBoolSetter.
It is unclear what causes some components to not export.

**To Reproduce**
1. Create an object with MapBoolSetter and give it a name
2. Launch the map, type `mapvar list` in console, and see that there's no variables.
3. Repeating this reproduction method with UnityExplorer installed, it is observed that the component wasn't on the object in the first place.

**Expected behavior**
The MapBoolSetter (in this case) to be in the level and to create a MapVar variable.

**General (please complete the following information):**
 - OS: [Windows 10]

**Editor (please complete the following information if editor-related):**
 - Unity [2019.4.40f1]
 - Enough disk space: [Yes]
 - Up to date: [Yes]

**Game (please complete the following information if game-related):**
 - Agony [2023.3.1]

**Comment by PITR-DEV** [comment]
This happens to components that aren't used in the base game. I have to manually add them to a dummy prefab to force Unity to include them. Please reopen this issue if any other scripts like that pop up.

**Comment by darkerbit** [comment]
More missing components at the moment:

- `Arena`: While primarily an editor extension, exporting it would be useful since it has code to auto-deactivate enemies that were accidentally left activatec
- `PlayerInputHooks`

**Comment by RedNova-therealonenotthefakeoneokay** [comment]
Another component I just discovered missing is Screenshaker and Camera Shake

**Comment by PITR-DEV** [comment]
This has been automated.
