### ISSUE TITLE
Drones bugged after destroying the idol blessing it

### ISSUE THREAD

**Issue by kekyoin7** [Tundra-Editor/Issues#42]
**Describe the bug**
When an idol blessing a drone is killed, the drone stops firing projectiles and creates many null reference errors every second 
The drone is parryable anytime after the bug, as if the process of the drone firing is interrupted, and the charge sound for the drone keeps looping

The error produced: 

NullReferenceException
UnityEngine.ParticleSystem.Play () (at <27fc6d13098248d699e0067444bf2b42>:0) Drone.Update () (at <e6de3f75082e4a168a533a01ddb5b516>:0)

**To Reproduce**
1. Have an idol bless a drone
2. Kill the idol

**Expected behavior**
The drone should behave like normal after the idol is destroyed

**Screenshots**
![image](https://user-images.githubusercontent.com/128580296/230578403-5abd6159-abed-49fb-b9db-54b07f2719d6.png)

**General (please complete the following information):**
 - OS: Windows 10

**Editor (please complete the following information if editor-related):**
 - Unity 2019.4.40f1
 - Enough disk space: [Yes]
 - Up to date: [Yes]

**Game (please complete the following information if game-related):**
 - Agony 2023.4.1 (Addressables update)

**Comment by PITR-DEV** [comment]
No repro
