### ISSUE TITLE
Having multiple shops in a level inexplicably breaks enemy explosions

### ISSUE THREAD

**Issue by William1321** [Tundra-Editor/Issues#55]
**Describe the bug**
Basically i'm doing this level with multiple shops in it and streetcleaner instakills wouldn't explode, cerberi projecitles wouldn't explode and interruptions didnt work and i spent SEVERAL hours banging my head against a wall trying to figure out why this was happening until debatable came in and helped me figure out that for some reason, having more than 1 shop in a level inexplicably breaks enemy explosions.

**To Reproduce**
1. Place a bunch of streetcleaners/cerberi/whatever
2. Place more than 1 shop terminal (in my case, i had one from the first room prefab and others elsewhere. even just one more shop causes aforementioned issues)
3. Export
4. See all enemies that use the default explosion break.

**Expected behavior**
Enemy explosions shouldn't break whenever there's more than 1 shop terminal

**Screenshots**
![image](https://github.com/Tundra-Editor/Issues/assets/128258352/bb003e4e-2611-4b25-8b3f-a487156b5069)
Screenshot of a NullReferenceException after trying to instakill a streetcleaner with more than 1 shop terminal in the map.

**General (please complete the following information):**
 - OS: Windows 10

**Editor (please complete the following information if editor-related):**
 - Unity 2019.4.40f1
 - Enough disk space: [Yes]
 - Up to date: [Yes]

**Game (please complete the following information if game-related):**
 - Agony 2023.5.2

**Additional context**
 We haven't pinpointed what exactly is causing this, but it seems to be related to the FirstRoom prefab shop. Not exactly useful to report this with such little info, however hopefully no one else has to bang their heads against a wall for hours trying to fix this.

**Comment by PITR-DEV** [comment]
I am unable to reproduce this in the latest version
