### ISSUE TITLE
Hitscan beams need a prefab update

### ISSUE THREAD

**Issue by wafflethings** [Tundra-Editor/Issues#57]
**Describe the bug**
The RevolverBeam script now has hitParticle as a AssetReference, not a GameObject. This breaks them, and means that Maurice beams don't explode.

**Screenshots**
![image](https://github.com/Tundra-Editor/Issues/assets/60797216/442b23a0-ccfe-4799-bbfd-b9cec41c0b06)

**Comment by William1321** [comment]
Technically already reported (issue 49) but this is still useful as it actually tells what the cause of the issue is
