### ISSUE TITLE
Turret beams are null

### ISSUE THREAD

**Issue by wafflethings** [Tundra-Editor/Issues#63]
**Describe the bug**
The beam of the turret is not loaded.

**To Reproduce**
1. Place a Turret in Tundra
2. Wait for it to fire
3. See no beam and a bunch of errors

**Expected behavior**
The turret shoots the beam.

**Screenshots**
![image](https://github.com/Tundra-Editor/Issues/assets/60797216/8e96f5d0-1d0d-4e62-bd13-e08d927099eb)

**Comment by wafflethings** [comment]
seems to be an issue with my map

**Comment by wafflethings** [comment]
nevermind, this is still an issue, the beam is seemingly not getting loaded, but only because my turrets are prefab variants, not the standard turret prefab.

placing a normal turret fixes it

**Comment by PITR-DEV** [comment]
I am unable to reproduce this issue.
Have you tried remaking your prefab variant from the actual updated prefab?

![image](https://github.com/Tundra-Editor/Issues/assets/13086471/677fc751-3c0f-4e1f-a435-5508d1229684)

https://github.com/Tundra-Editor/Issues/assets/13086471/b66c511d-c017-4f98-bf66-0f36a7681098
